In [2]:
import pandas as pd

In [3]:
pd.__version__

'3.0.3'

### Dataframe

##### Create Dataframe

In [6]:
df = pd.DataFrame([11, 22, 33], columns=['Col_Name'])
print(df)

   Col_Name
0        11
1        22
2        33

In [7]:
print(type(df))

<class 'pandas.DataFrame'>

In [8]:
data = {
    'Name': ['Madhav', 'Vishakha', 'Lalita', 'Rishabh'],
    'Age': [16, 17, 18, 19],
    'Salary': [90000, 70000, 50000, 30000]
}

In [9]:
df = pd.DataFrame(data)
print(df)

       Name  Age  Salary
0    Madhav   16   90000
1  Vishakha   17   70000
2    Lalita   18   50000
3   Rishabh   19   30000

In [10]:
print(type(df))

<class 'pandas.DataFrame'>

##### Basic Dataframe understanding

In [12]:
df.head(2) # top rows

       Name  Age  Salary
0    Madhav   16   90000
1  Vishakha   17   70000

In [13]:
df.tail(2) # last rows

      Name  Age  Salary
2   Lalita   18   50000
3  Rishabh   19   30000

In [15]:
df.shape

(4, 3)

In [16]:
df.columns

Index(['Name', 'Age', 'Salary'], dtype='str')

In [20]:
df.rename(columns={'Salary': 'Monthly_Salary'}, inplace=True)

In [21]:
df

       Name  Age  Monthly_Salary
0    Madhav   16           90000
1  Vishakha   17           70000
2    Lalita   18           50000
3   Rishabh   19           30000

In [22]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            4 non-null      str
 1   Age             4 non-null      int64
 2   Monthly_Salary  4 non-null      int64
dtypes: int64(2), str(1)
memory usage: 228.0 bytes

In [23]:
df.describe()

             Age  Monthly_Salary
count   4.000000        4.000000
mean   17.500000    60000.000000
std     1.290994    25819.888975
min    16.000000    30000.000000
25%    16.750000    45000.000000
50%    17.500000    60000.000000
75%    18.250000    75000.000000
max    19.000000    90000.000000

##### Save and load data from csv

In [27]:
df.to_csv('Test_data.csv', index=False)

In [29]:
load_df = pd.read_csv('Test_data.csv')
load_df

       Name  Age  Monthly_Salary
0    Madhav   16           90000
1  Vishakha   17           70000
2    Lalita   18           50000
3   Rishabh   19           30000

##### Rows and Columns Selection

In [31]:
# Select column

# df[['Name']] # Single Column
df[['Name', 'Monthly_Salary']]

       Name  Monthly_Salary
0    Madhav           90000
1  Vishakha           70000
2    Lalita           50000
3   Rishabh           30000

In [ ]:
# Select rows

# loc - label based
# df.loc[df.Name=='Madhav']
df.loc[(df.Name=='Madhav') & (df.Monthly_Salary>=5000)]

     Name  Age  Monthly_Salary
0  Madhav   16           90000

In [36]:
# iloc - index value based
df.iloc[0]
df.iloc[0:2]

       Name  Age  Monthly_Salary
0    Madhav   16           90000
1  Vishakha   17           70000

In [37]:
df.loc[0:2]

       Name  Age  Monthly_Salary
0    Madhav   16           90000
1  Vishakha   17           70000
2    Lalita   18           50000

##### filter dataframe

In [42]:
df_age_filter = df[df['Age'] >= 18]
df_age_filter

      Name  Age  Monthly_Salary
2   Lalita   18           50000
3  Rishabh   19           30000

In [43]:
df[(df['Age'] >= 18) & (df['Monthly_Salary'] >= 50000)]

     Name  Age  Monthly_Salary
2  Lalita   18           50000

In [44]:
df.where(df['Age'] >= 18)

      Name   Age  Monthly_Salary
0      NaN   NaN             NaN
1      NaN   NaN             NaN
2   Lalita  18.0         50000.0
3  Rishabh  19.0         30000.0

In [45]:
df.where(df['Age'] >= 18, other = 'Not Eligible')

           Name           Age Monthly_Salary
0  Not Eligible  Not Eligible   Not Eligible
1  Not Eligible  Not Eligible   Not Eligible
2        Lalita            18          50000
3       Rishabh            19          30000

##### Rows and columns - Operations (Add, Update, Delete)

In [46]:
df

       Name  Age  Monthly_Salary
0    Madhav   16           90000
1  Vishakha   17           70000
2    Lalita   18           50000
3   Rishabh   19           30000

In [48]:
# add new column
df['Team'] = ['CEO', 'HR', 'CTO', 'DA']
df

       Name  Age  Monthly_Salary Team
0    Madhav   16           90000  CEO
1  Vishakha   17           70000   HR
2    Lalita   18           50000  CTO
3   Rishabh   19           30000   DA

In [68]:
df['Bonus'] = df['Monthly_Salary'] * 0.2
df

       Name  Age  Monthly_Salary Team    Bonus
0    Madhav   16           90000  CEO  18000.0
1  Vishakha   17           70000   HR  14000.0
2    Lalita   18           50000  CTO  10000.0
3   Rishabh   19           30000   DA   6000.0

In [69]:
# add new row
df.loc[len(df)] = ['ABC', 21, 21000, 'IT', 2000]
df

       Name  Age  Monthly_Salary Team    Bonus
0    Madhav   16           90000  CEO  18000.0
1  Vishakha   17           70000   HR  14000.0
2    Lalita   18           50000  CTO  10000.0
3   Rishabh   19           30000   DA   6000.0
4       ABC   21           21000   IT   2000.0

In [70]:
len(df)

5

In [71]:
# update value

df.loc[0, 'Monthly_Salary'] = 95000
df

       Name  Age  Monthly_Salary Team    Bonus
0    Madhav   16           95000  CEO  18000.0
1  Vishakha   17           70000   HR  14000.0
2    Lalita   18           50000  CTO  10000.0
3   Rishabh   19           30000   DA   6000.0
4       ABC   21           21000   IT   2000.0

In [72]:
# update value - using column value
df.loc[df.Name == 'Madhav', 'Monthly_Salary'] = 90000

In [73]:
# delete value - row and column value

df.drop(df[df.Name == 'ABC'].index, inplace=True) # drop row, axis = 0
df

       Name  Age  Monthly_Salary Team    Bonus
0    Madhav   16           90000  CEO  18000.0
1  Vishakha   17           70000   HR  14000.0
2    Lalita   18           50000  CTO  10000.0
3   Rishabh   19           30000   DA   6000.0

In [75]:
df.drop(1, axis=0) # index name

      Name  Age  Monthly_Salary Team
0   Madhav   16           90000  CEO
2   Lalita   18           50000  CTO
3  Rishabh   19           30000   DA

In [74]:
df.drop('Bonus', axis=1, inplace=True)
df

       Name  Age  Monthly_Salary Team
0    Madhav   16           90000  CEO
1  Vishakha   17           70000   HR
2    Lalita   18           50000  CTO
3   Rishabh   19           30000   DA

##### sort value

In [ ]:
df.sort_values('Monthly_Salary') # ascending order by default

       Name  Age  Monthly_Salary Team
3   Rishabh   19           30000   DA
2    Lalita   18           50000  CTO
1  Vishakha   17           70000   HR
0    Madhav   16           90000  CEO

In [77]:
df.sort_values('Monthly_Salary', ascending=False)

       Name  Age  Monthly_Salary Team
0    Madhav   16           90000  CEO
1  Vishakha   17           70000   HR
2    Lalita   18           50000  CTO
3   Rishabh   19           30000   DA

##### Working with date value

In [78]:
df['DOJ'] = ['2024-01-01', '2024-01-15', '2024-03-28', '2024-03-03']
df

       Name  Age  Monthly_Salary Team         DOJ
0    Madhav   16           90000  CEO  2024-01-01
1  Vishakha   17           70000   HR  2024-01-15
2    Lalita   18           50000  CTO  2024-03-28
3   Rishabh   19           30000   DA  2024-03-03

In [79]:
df['DOJ'].dtype

In [80]:
df['DOJ'] = pd.to_datetime(df['DOJ'])

In [81]:
df['DOJ'].dtype

dtype('<M8[us]')

In [101]:
df1 = df

In [102]:
df1['DOJ2'] = ['01-01-2025', '15-01-2025', '28-03-2025', '03-03-2025']
df1

       Name  Age  Monthly_Salary Team        DOJ        DOJ2
0    Madhav   16           90000  CEO 2024-01-01  01-01-2025
1  Vishakha   17           70000   HR 2024-01-15  15-01-2025
2    Lalita   18           50000  CTO 2024-03-28  28-03-2025
3   Rishabh   19           30000   DA 2024-03-03  03-03-2025

In [103]:
df1['DOJ2'].dtype

In [104]:
df1['DOJ2'] = pd.to_datetime(df1['DOJ2'], format = '%d-%m-%Y')

In [105]:
df1['DOJ2'].dtype

dtype('<M8[us]')

In [106]:
df = df.drop('DOJ2', axis=1)
df

       Name  Age  Monthly_Salary Team        DOJ
0    Madhav   16           90000  CEO 2024-01-01
1  Vishakha   17           70000   HR 2024-01-15
2    Lalita   18           50000  CTO 2024-03-28
3   Rishabh   19           30000   DA 2024-03-03

In [108]:
# extract year, month, week, day
df['DOJ'].dt.year
df['DOJ'].dt.month
df['DOJ'].dt.day
df['DOJ'].dt.day_name()

0      Monday
1      Monday
2    Thursday
3      Sunday
Name: DOJ, dtype: str

In [109]:
df['Month'] = df['DOJ'].dt.month
df

       Name  Age  Monthly_Salary Team        DOJ  Month
0    Madhav   16           90000  CEO 2024-01-01      1
1  Vishakha   17           70000   HR 2024-01-15      1
2    Lalita   18           50000  CTO 2024-03-28      3
3   Rishabh   19           30000   DA 2024-03-03      3

In [111]:
df['DOJ'] + pd.Timedelta(days=90)

0   2024-03-31
1   2024-04-14
2   2024-06-26
3   2024-06-01
Name: DOJ, dtype: datetime64[us]

##### Handling missing values

In [112]:
df

       Name  Age  Monthly_Salary Team        DOJ  Month
0    Madhav   16           90000  CEO 2024-01-01      1
1  Vishakha   17           70000   HR 2024-01-15      1
2    Lalita   18           50000  CTO 2024-03-28      3
3   Rishabh   19           30000   DA 2024-03-03      3

In [113]:
df.isnull()

    Name    Age  Monthly_Salary   Team    DOJ  Month
0  False  False           False  False  False  False
1  False  False           False  False  False  False
2  False  False           False  False  False  False
3  False  False           False  False  False  False

In [114]:
import numpy as np

In [117]:
df.loc[df.Name == 'Rishabh', 'Monthly_Salary'] = np.nan
df

       Name  Age  Monthly_Salary Team        DOJ  Month
0    Madhav   16         90000.0  CEO 2024-01-01      1
1  Vishakha   17         70000.0   HR 2024-01-15      1
2    Lalita   18         50000.0  CTO 2024-03-28      3
3   Rishabh   19             NaN   DA 2024-03-03      3

In [118]:
df.isnull()

    Name    Age  Monthly_Salary   Team    DOJ  Month
0  False  False           False  False  False  False
1  False  False           False  False  False  False
2  False  False           False  False  False  False
3  False  False            True  False  False  False

In [119]:
df.isnull().sum()

Name              0
Age               0
Monthly_Salary    1
Team              0
DOJ               0
Month             0
dtype: int64

In [120]:
df.fillna(0)

       Name  Age  Monthly_Salary Team        DOJ  Month
0    Madhav   16         90000.0  CEO 2024-01-01      1
1  Vishakha   17         70000.0   HR 2024-01-15      1
2    Lalita   18         50000.0  CTO 2024-03-28      3
3   Rishabh   19             0.0   DA 2024-03-03      3

##### Aggregation and groupby

In [124]:
df[df['Month'] == 1].value_counts()

Name      Age  Monthly_Salary  Team  DOJ         Month
Madhav    16   90000.0         CEO   2024-01-01  1        1
Vishakha  17   70000.0         HR    2024-01-15  1        1
Name: count, dtype: int64

In [126]:
df.groupby('Month')['Monthly_Salary'].sum()

Month
1    160000.0
3     50000.0
Name: Monthly_Salary, dtype: float64

In [128]:
df.groupby('Month').agg({'Monthly_Salary': 'mean', 'Name': 'count'})

       Monthly_Salary  Name
Month
1             80000.0     2
3             50000.0     2

##### Concatenate and Merge Dataframe

In [129]:
df1 = pd.DataFrame({'ID':[1,2,3],'Name':['A','B','C']})
df1

   ID Name
0   1    A
1   2    B
2   3    C

In [130]:
df2 = pd.DataFrame({'ID':[1,2,2,4],'Score':[88,96,77,79]})
df2

   ID  Score
0   1     88
1   2     96
2   2     77
3   4     79

In [132]:
pd.concat([df1, df2], axis=0) # vertical/ row level/ top on top

   ID Name  Score
0   1    A    NaN
1   2    B    NaN
2   3    C    NaN
0   1  NaN   88.0
1   2  NaN   96.0
2   2  NaN   77.0
3   4  NaN   79.0

In [134]:
pd.concat([df1, df2], axis=1) # horizontal / column level / side by side

    ID Name  ID  Score
0  1.0    A   1     88
1  2.0    B   2     96
2  3.0    C   2     77
3  NaN  NaN   4     79

In [135]:
# merge = join
pd.merge(df1, df2, how='inner', on='ID')

   ID Name  Score
0   1    A     88
1   2    B     96
2   2    B     77

In [136]:
pd.merge(df1, df2, how='left', on='ID')

   ID Name  Score
0   1    A   88.0
1   2    B   96.0
2   2    B   77.0
3   3    C    NaN

In [137]:
pd.merge(df1, df2, how='right', on='ID')

   ID Name  Score
0   1    A     88
1   2    B     96
2   2    B     77
3   4  NaN     79

In [139]:
pd.merge(df1, df2, how='inner', left_on='ID', right_on='ID')

   ID Name  Score
0   1    A     88
1   2    B     96
2   2    B     77

##### AI and chatgpt